spring:
  application:
<<<<<<< HEAD
    name: ulkeler
  profiles:
    active: dev
=======
    name: countries-be
  profiles:
    active: dev

server:
  port: 8181

logging:
  level:
    root: error
>>>>>>> c45717c52eeb4f6a0abdb979bd514b096339620c
